export const questions = [
    { id: 'q1', type: "boolean", text: `Самая большая жемчужина в мире весит 6 кг.`, correctAnswer: true },
    { id: 'q2', type: "boolean", text: `В США до 1913 года разрешалось отправлять детей по почте.`, correctAnswer: true },
    { id: 'q3', type: "boolean", text: `В топ-250 лучших фильмов, по мнению американской киноакадемии входят 12 советских/российских картин`, correctAnswer: false },
    { id: 'q4', type: "boolean", text: `В конце 2023 года песня Шамана "Я Русский" возглавила мировой рейтинг Shazam`, correctAnswer: false },
    { id: 'q5', type: "boolean", text: `В древнегреческом языке было 14 слов для обозначения религии`, correctAnswer: false },
    { id: 'q6', type: "boolean", text: `В Ирландии никогда не было кротов`, correctAnswer: true },
    { id: 'q7', type: "boolean", text: `Самый маленький динозавр был размером с желудь`, correctAnswer: false },
    { id: 'q8', type: "boolean", text: `Роберт Льюс Стивенсон описал одного из героев "Острова Сокровищ" с тогдашнего премьер министра Великобритании Бенджамина Дизраэли`, correctAnswer: false },
    { id: 'q9', type: "boolean", text: `Во Франции до начала XIX века не праздновали Новый Год`, correctAnswer: false },
    { id: 'q10', type: "boolean", text: `Корова может подняться по лестнице, но не может спуститься`, correctAnswer: true },
    { id: 'q11', type: "boolean", text: `В Австралии есть паук, умеющий подражать человеческому голосу`, correctAnswer: false },
    { id: 'q12', type: "boolean", text: `Первые десять экранизаций романа "12 стульев" были сделаны за рубежом`, correctAnswer: true },
    { id: 'q13', type: "boolean", text: `В списке из 10 самых опасных пород собак питбуль стоит выше волкособа `, correctAnswer: false },
    { id: 'q14', type: "boolean", text: `Коктейль "отвертка" это русское облагороженное название американского коктейля "секс с водителем"`, correctAnswer: false },
    { id: 'q15', type: "boolean", text: `в 90-х годах до сериала Бригада Дмитрий Дюжев снялся в четерех эротических фильмах`, correctAnswer: false },
    { id: 'q16', type: "boolean", text: `Шотландское пиво Beithir Fire имеет крепость 75 градусов`, correctAnswer: true },
    { id: 'q17', type: "boolean", text: `На гербе города Шуи изображен просто кусок мыла`, correctAnswer: true },
    { id: 'q18', type: "boolean", text: `Клумпакоис это название танца`, correctAnswer: true },
    { id: 'q19', type: "boolean", text: `Настоящая фамилия актера Игоря Верника - Шайгець`, correctAnswer: false },
    { id: 'q20', type: "boolean", text: `Фильм "28 дней спустя" назван так, потому что был снят за 28 дней`, correctAnswer: true },
    { id: 'q21', type: "boolean", text: `В Красноярском метро всего четыре станции`, correctAnswer: false },
    { id: 'q22', type: "boolean", text: `В одной молекуле воды больше атомов водорода, чем звезд в солнечной системе`, correctAnswer: true },
    { id: 'q23', type: "boolean", text: `Площадь Австралии больше площади Канады`, correctAnswer: false },
    { id: 'q24', type: "boolean", text: `В Таиланде нельзя писать красным цветом имена живых людей`, correctAnswer: true },
    { id: 'q25', type: "boolean", text: `Бухалово это деревня в Ярославской области`, correctAnswer: true },
    { id: 'q26', type: "boolean", text: `Алла Агеева - настоящее имя Маши Распутиной`, correctAnswer: true },
    { id: 'q27', type: "boolean", text: `На конец 2024 года в сериале "Тайны следствия" больше серий чем в сериале "Санта Барбара"`, correctAnswer: false },
    { id: 'q28', type: "boolean", text: `Манкурты - род степных грызунов семейства беличьих`, correctAnswer: false },
    { id: 'q29', type: "boolean", text: `Хорофобия это страх танцев`, correctAnswer: true },
    { id: 'q30', type: "boolean", text: `Имена Антон и Антонио происходят от разных слов`, correctAnswer: false },
    { id: 'q31', type: "boolean", text: `Николай Валуев выступал в балете в труппе Большого Театра в сезоне 2019-2020`, correctAnswer: false },
    { id: 'q32', type: "boolean", text: `Человеческий геном на 40% совпадает с геномом огурца`, correctAnswer: true },
    { id: 'q33', type: "boolean", text: `В високосном 2420 году в феврале будет не 29, а 28 дней, для коррекции календаря`, correctAnswer: false },
    { id: 'q34', type: "boolean", text: `Актер Крис Хэмсворт раньше работал чистильщиком использованных молокоотсосов`, correctAnswer: true },
    { id: 'q35', type: "boolean", text: `Оганесон - 118й элемент переодической системы Менделеева`, correctAnswer: true },
    { id: 'q36', type: "boolean", text: `в 1996 году трэк Любэ "Батяня-комбат" продержался суммарно более двух недель в музыкальных чартах Великобритании `, correctAnswer: false },
    { id: 'q37', type: "boolean", text: `В Таиланде существует закон, запрещающий выходить из дома без нижнего белья`, correctAnswer: true },
    { id: 'q38', type: "boolean", text: `Клеопатра жила ближе к временам, когда были живы мамонты, чем к нашим временам`, correctAnswer: true },
    { id: 'q39', type: "boolean", text: `Лед-9 это форма льда, образующего не шестигранные, а девятигранные кристаллы `, correctAnswer: false },
    { id: 'q40', type: "boolean", text: `"Омон Ра" это книга про советскую космонавтику`, correctAnswer: true },
    { id: 'q41', type: "boolean", text: `В Китае запрещено использовать единицу измерения дециметр`, correctAnswer: false },
    { id: 'q42', type: "boolean", text: `В Европе инструмент "болгарку" называют "russian grinder"`, correctAnswer: false },
]
