export const questions = [
    { question: `Самая большая жемчужина в мире весит 6 кг.`, correctAnswer: true },
    { question: `В США до 1913 года разрешалось отправлять детей по почте.`, correctAnswer: true },
    { question: `В топ-250 лучших фильмов, по мнению американской киноакадемии входят 12 советских/российских картин`, correctAnswer: false },
    { question: `В конце 2023 года песня Шамана "Я Русский" возглавила мировой рейтинг Shazam`, correctAnswer: false },
    { question: `В древнегреческом языке было 14 слов для обозначения религии`, correctAnswer: false },
    { question: `В Ирландии никогда не было кротов`, correctAnswer: true },
    { question: `Самый маленький динозавр был размером с желудь`, correctAnswer: false },
    { question: `Роберт Льюс Стивенсон описал одного из героев "Острова Сокровищ" с тогдашнего премьер министра Великобритании Бенджамина Дизраэли`, correctAnswer: false },
    { question: `Во Франции до начала XIX века не праздновали Новый Год`, correctAnswer: false },
    { question: `Корова может подняться по лестнице, но не может спуститься`, correctAnswer: true },
    { question: `В Австралии есть паук, умеющий подражать человеческому голосу`, correctAnswer: false },
    { question: `Первые десять экранизаций романа "12 стульев" были сделаны за рубежом`, correctAnswer: true },
    { question: `В списке из 10 самых опасных пород собак питбуль стоит выше волкособа `, correctAnswer: false },
    { question: `Коктейль "отвертка" это русское облагороженное название американского коктейля "секс с водителем"`, correctAnswer: false },
    { question: `в 90-х годах до сериала Бригада Дмитрий Дюжев снялся в четерех эротических фильмах`, correctAnswer: false },
    { question: `Шотландское пиво Beithir Fire имеет крепость 75 градусов`, correctAnswer: true },
    { question: `На гербе города Шуи изображен просто кусок мыла`, correctAnswer: true },
    { question: `Клумпакоис это название танца`, correctAnswer: true },
    { question: `Настоящая фамилия актера Игоря Верника - Шайгець`, correctAnswer: false },
    { question: `Фильм "28 дней спустя" назван так, потому что был снят за 28 дней`, correctAnswer: true },
    { question: `В Красноярском метро всего четыре станции`, correctAnswer: false },
    { question: `В одной молекуле воды больше атомов водорода, чем звезд в солнечной системе`, correctAnswer: true },
    { question: `Площадь Австралии больше площади Канады`, correctAnswer: false },
    { question: `В Таиланде нельзя писать красным цветом имена живых людей`, correctAnswer: true },
    { question: `Бухалово это деревня в Ярославской области`, correctAnswer: true },
    { question: `Алла Агеева - настоящее имя Маши Распутиной`, correctAnswer: true },
    { question: `На конец 2024 года в сериале "Тайны следствия" больше серий чем в сериале "Санта Барбара"`, correctAnswer: false },
    { question: `Манкурты - род степных грызунов семейства беличьих`, correctAnswer: false },
    { question: `Хорофобия это страх танцев}`, correctAnswer: true },
    { question: `Имена Антон и Антонио происходят от разных слов`, correctAnswer: false },
    { question: `Николай Валуев выступал в балете в труппе Большого Театра в сезоне 2019-2020`, correctAnswer: false },
    { question: `Человеческий геном на 40% совпадает с геномом огурца`, correctAnswer: true },
    { question: `В високосном 2420 году в феврале будет не 29, а 28 дней, для коррекции календаря`, correctAnswer: false },
    { question: `Актер Крис Хэмсворт раньше работал чистильщиком использованных молокоотсосов`, correctAnswer: true },
    { question: `Оганесон - 118й элемент переодической системы Менделеева`, correctAnswer: true },
    { question: `в 1996 году трэк Любэ "Батяня-комбат" продержался суммарно более двух недель в музыкальных чартах Великобритании `, correctAnswer: false },
    { question: `В Таиланде существует закон, запрещающий выходить из дома без нижнего белья`, correctAnswer: true },
    { question: `Клеопатра жила ближе к временам, когда были живы мамонты, чем к нашим временам`, correctAnswer: true },
    { question: `Лед-9 это форма льда, образующего не шестигранные, а девятигранные кристаллы `, correctAnswer: false },
    { question: `"Омон Ра" это книга про советскую космонавтику`, correctAnswer: true },
    { question: `В Китае запрещено использовать единицу измерения дециметр`, correctAnswer: false },
    { question: `В Европе инструмент "болгарку" называют "russian grinder"`, correctAnswer: false },
]
